[package]
name = "calibornia-discord-bot"
version = "0.1.0"
edition = "2024"
description = "Discord bot for the Calibornia Discord"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1"
regex = "1"
serenity = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
